# Generated by Django 4.2 on 2023-04-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voditels',
            name='number_avto',
        ),
    ]
