# Generated by Django 4.2 on 2023-04-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0002_remove_voditels_number_avto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voditels',
            name='number_prav',
            field=models.CharField(max_length=15, unique=True, verbose_name='number_prav'),
        ),
    ]
