# Generated by Django 4.2 on 2023-04-17 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0003_alter_voditels_number_prav'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50, verbose_name='marka')),
                ('model', models.CharField(max_length=50, verbose_name='model')),
                ('data_vypuska', models.DateField(verbose_name='data_vypuska')),
                ('vin_number', models.CharField(max_length=25, unique=True, verbose_name='vin_number')),
                ('number_avto', models.CharField(max_length=15, verbose_name='number_avto')),
                ('probeg', models.CharField(max_length=15, verbose_name='probeg')),
                ('voditels', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='avto.voditels')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
