# Generated by Django 4.2 on 2023-04-17 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0004_cars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strahovki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sobstvennik_avto', models.CharField(max_length=15, verbose_name='sobstvennik_avto')),
                ('data_nachala', models.DateField(verbose_name='data_nachala')),
                ('data_conca', models.DateField(verbose_name='data_conca')),
                ('number_polisa', models.CharField(max_length=15, verbose_name='number_polisa')),
                ('cars', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='avto.cars')),
            ],
            options={
                'verbose_name': 'Страховка',
                'verbose_name_plural': 'Страховки',
            },
        ),
    ]
