# Generated by Django 4.2 on 2023-04-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0006_techosmotr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strahovki',
            name='number_polisa',
            field=models.CharField(max_length=15, unique=True, verbose_name='number_polisa'),
        ),
        migrations.AlterField(
            model_name='techosmotr',
            name='number_tex_karty',
            field=models.CharField(max_length=15, unique=True, verbose_name='number_tex_karty'),
        ),
    ]
