# Generated by Django 4.2 on 2023-04-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0007_alter_strahovki_number_polisa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strahovki',
            name='sobstvennik_avto',
            field=models.CharField(max_length=50, verbose_name='sobstvennik_avto'),
        ),
        migrations.AlterField(
            model_name='techosmotr',
            name='zakazchik',
            field=models.CharField(max_length=50, verbose_name='zakazchik'),
        ),
    ]
